<?php
//instanciando as classes
//require_once './../Model/Categoria.php';
//require_once './../Model/Subcategoria.php';
//require_once './../Controller/CategoriaController.php';
//require_once './../Controller/SubcategoriaController.php';
//require_once './../Util/Helper.php';


$categoria = new Categoria();
$subcategoria = new Subcategoria();
$categoriaController = new CategoriaController();
$subcategoriaController = new SubcategoriaController();
$helper = new Helper();

//exibir a msg de resultado 
$resultado = "";

$listarCategoria = $categoriaController->ListarTodasCategorias(0,200);

//$cod para fazer atualização da subcategoria
$cod = filter_input(INPUT_GET, 'update', FILTER_SANITIZE_STRING);
$btnCadastrar = filter_input(INPUT_POST, "btnAtualizar", FILTER_SANITIZE_STRING);
if ($btnCadastrar):
    $subcategoria->setSub_cod($cod);
    $subcategoria->setSub_titulo(filter_input(INPUT_POST, "txtTitulo", FILTER_SANITIZE_STRING));
    $txtUrl = Helper::Name($subcategoria->getSub_titulo());
    $subcategoria->setSub_url($txtUrl);
    $subcategoria->setSub_status(filter_input(INPUT_POST, "slStatus", FILTER_SANITIZE_NUMBER_INT));
    $subcategoria->setSub_descricao(filter_input(INPUT_POST, "txtDescricao", FILTER_SANITIZE_STRING)); 
    
    $subcategoria->setCategoria(filter_input(INPUT_POST, "slCategoria", FILTER_SANITIZE_NUMBER_INT));  
    
    if ($subcategoriaController->Atualizar($subcategoria)):
        $insertGoTo = '?pagina=listarSubcategoria';
        header("refresh:2;url={$insertGoTo}");
        $resultado = '<div class="alert alert-info">        
        <span><b> Atualizado com sucesso - </b></span>
        </div>';
    else:
        $resultado = '<div class="alert alert-danger">        
        <span><b> Erro ao atualizar, tente mais tarde - </b></span>
        </div>';
    endif; 
endif;



//retorna dados da subcategoria
$retornaSubcategoria = $subcategoriaController->retornaSubcategoria($cod);
if ($retornaSubcategoria == null):
else:
    $titulo = $retornaSubcategoria->getSub_titulo();
    $status = $retornaSubcategoria->getSub_status();
    $descricao = $retornaSubcategoria->getSub_descricao();    
    $categoriaCod = $retornaSubcategoria->getCategoria()->getCod();
    $categoriaTitulo = $retornaSubcategoria->getCategoria()->getTitulo();  
?>


<div class="main-panel">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="#">Subcategoria Atualizar</a>
            </div>
              <?php require_once './inc/header_top.php'; ?>
        </div>
    </nav>


    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12 col-md-7">

                    <div class="card">
                        <div class="header">
                            <h4 class="title">Subcategoria</h4>                           
                        </div>
                        <div class="content">
                            <form method="post">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>Título</label>
                                            <input type="text" name="txtTitulo" class="form-control border-input" placeholder="Título da Categoria" value="<?= $titulo ?>">
                                        </div>
                                    </div>
                                    
                                    <div class="col-md-3">
                                            <div class="form-group">
                                                <label for="exampleInputEmail1">Categoria</label>
                                                <select name="slCategoria" class="form-control border-input">
                                                    <option value="<?= $categoriaCod; ?>"><?= $categoriaTitulo; ?></option>                                                    
                                                    <?php                                                    
                                                    foreach ($listarCategoria as $cat):
                                                        if ($cat->getTitulo() == $categoriaTitulo):
                                                        else:
                                                            echo "<option value=\"{$cat->getCod()}\">{$cat->getTitulo()}</option>";
                                                        endif;
                                                    endforeach;
                                                    ?>
                                                </select>

                                            </div>
                                    </div>
                                    
                                    <div class="col-md-3">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">Status</label>
                                            <select name="slStatus" class="form-control border-input">
                                                <?php
                                                    if ($status == 1):
                                                            ?>
                                                            <option value="1" selected='selected'>Ativo</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="2" selected='selected'>Bloqueado</option>
                                                        <?php
                                                        endif;
                                                        if ($status != 1):
                                                            ?>
                                                            <option value="1" <?php $status == 1 ? "selected='selected'" : "" ?>>Ativo</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="2" <?php $status == 2 ? "selected='selected'" : "" ?>>Bloqueado</option>
                                                        <?php
                                                        endif;
                                                    ?>
                                            </select>

                                        </div>
                                    </div>
                                </div>

                                <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Descrição </label>
                                                <input type="text" name="txtDescricao" class="form-control border-input" placeholder="Título da Categoria" value="<?= $descricao ?>">
                                            </div>
                                        </div>                                   

                                </div>
                                

                                <div class="row">
                                    <div class="col-md-12">
                                        <?php echo $resultado; ?>
                                    </div>

                                </div>                               


                                <div class="text-center">
                                    <input type="submit" class="btn btn-success btn-fill btn-wd" name="btnAtualizar" value="Atualizar">

                                </div>
                                <div class="clearfix"></div>
                            </form>
                        </div>
                    </div>

                </div>


            </div>
        </div>
    </div>

<?php
endif;
?>