<?php
//chamando as classes
$produto = new Produto();
$helper = new Helper();
$upload = new Upload();

$produtoController = new ProdutoController();
$categoriaController = new CategoriaController();
$subcategoriaController = new SubcategoriaController();
$variacaoController = new VariacaoController();


//mostra a mensagem verdadeiro ou falso na hora do cadastro
$resultado = "";

//alteração da imagem
$submitImage = filter_input(INPUT_POST, 'submitImage', FILTER_SANITIZE_STRING);
if ($submitImage):
    $cod = filter_input(INPUT_GET, 'cod', FILTER_VALIDATE_INT);

    $retornaImagem = $produtoController->retornaProdutoImagem($cod);
    $thumbProd = $retornaImagem->getThumb();
    $nomeProd = $retornaImagem->getTitulo();   

    $capa = "../upload/" . $thumbProd;
    if (file_exists($capa) && !is_dir($capa)):
        unlink($capa);
    endif;
    //imagem esta recebendo files imagemArtigo
    $imagem = $_FILES['imagemArtigo'];
    //recebendo a imagem, nome do produto, tamanho da imagem, pasta
    $upload->Image($imagem, $nomeProd, 1000, 'produtos');
    //setando a imagem
    $nomeImagem = $upload->getResult();
    $produto->setThumb($nomeImagem);

    if ($produtoController->AlterarImagem($cod, $nomeImagem)):
        $insertGoTo = '?pagina=listarProduto';
        header("refresh:2;url={$insertGoTo}");
        $resultado = "<div class=\"alert alert-success\">A imagem <b>{$nomeImagem} </b> foi alterado com sucesso</div>";
    else:
        $insertGoTo = '?pagina=produto';
        header("refresh:2;url={$insertGoTo}");
        $resultado = "<div class=\"alert alert-danger\">Erro ao cadastrar </div>";
    endif;
endif;

//alteração do post                             
$btnCadastrar = filter_input(INPUT_POST, 'btnCadastrar', FILTER_SANITIZE_STRING);
if ($btnCadastrar):

    $cod = filter_input(INPUT_GET, 'cod', FILTER_VALIDATE_INT);
    $produto->setCod($cod);
    $produto->setTitulo(filter_input(INPUT_POST, 'txtTitulo', FILTER_SANITIZE_STRING));
    $url = $helper->Name($produto->getTitulo());
    $produto->setUrl($url);
    $produto->setCategoria(filter_input(INPUT_POST, 'slCategoria', FILTER_SANITIZE_NUMBER_INT));
    $produto->setCod_ra(filter_input(INPUT_POST, 'slCodRa', FILTER_SANITIZE_STRING));
    $produto->setVariacao(filter_input(INPUT_POST, 'slVariacao', FILTER_SANITIZE_NUMBER_INT));
    $produto->setOferta(filter_input(INPUT_POST, 'slOferta', FILTER_SANITIZE_NUMBER_INT));    
    $produto->setSubcategoria(filter_input(INPUT_POST, 'slSubcategoria', FILTER_SANITIZE_NUMBER_INT));
    $produto->setStatus(filter_input(INPUT_POST, 'slStatus', FILTER_SANITIZE_NUMBER_INT));
    $produto->setDescricao(filter_input(INPUT_POST, 'txtDescricao', FILTER_SANITIZE_SPECIAL_CHARS));
    $produto->setValor(filter_input(INPUT_POST, 'txtPreco', FILTER_SANITIZE_STRING));
    $produto->setValor_antigo(filter_input(INPUT_POST, 'txtValor_antigo', FILTER_SANITIZE_STRING));
    $produto->setDesconto(filter_input(INPUT_POST, 'txtDesconto', FILTER_SANITIZE_STRING));
    $produto->setMarca_do_produto(filter_input(INPUT_POST, 'txtMarca', FILTER_SANITIZE_STRING));
    $produto->setEstoque(filter_input(INPUT_POST, 'txtEstoque', FILTER_SANITIZE_NUMBER_INT));
    $produto->setData(date('Y-m-d H:i:s'));



    //Alterar do produto
    if ($produtoController->Atualizar($produto)):
        $insertGoTo = '?pagina=listarProduto';
        header("refresh:2;url={$insertGoTo}");
        $resultado = '<div class="alert alert-success">
                        <button type="button" aria-hidden="true" class="close">×</button>
                        <span><b> Atualizado efetuado com sucesso - </b></span>
                    </div>';
    else:
        $insertGoTo = '?pagina=editarProduto';
        header("refresh:2;url={$insertGoTo}");
        $resultado = '<div class="alert alert-danger">
                        <button type="button" aria-hidden="true" class="close">×</button>
                        <span><b> Erro ao Atualizar - Favor preencha todos os campos</b></span>
                    </div>';
    endif;

endif;

//retornando os dados para o formulário - atraves do get COD
$cod = filter_input(INPUT_GET, 'cod', FILTER_VALIDATE_INT);
$retornaProduto = $produtoController->retornaIdProduto($cod);

if ($retornaProduto == NULL):

else:
    $nome = $retornaProduto->getTitulo();
    $descricao = $retornaProduto->getDescricao();
    $ra = $retornaProduto->getCod_ra();
    $oferta = $retornaProduto->getOferta();
    $preco = $retornaProduto->getValor();
    $estoque = $retornaProduto->getEstoque();
    $thumb = $retornaProduto->getThumb();
    $status = $retornaProduto->getStatus();
    $valor_antigo = $retornaProduto->getValor_antigo();
    $desconto = $retornaProduto->getDesconto();
    $marca = $retornaProduto->getMarca_do_produto();    

    //pegando os dados da variacao
    $varCod = $retornaProduto->getVariacao()->getCod_variavel();
    $varTitle = $retornaProduto->getVariacao()->getTitulo_variavel();

    //pegando os dados da categoria
    $categCod = $retornaProduto->getCategoria()->getCod();
    $categTitle = $retornaProduto->getCategoria()->getTitulo();
    //pegando os dados da Subcategoria
    $subCod = $retornaProduto->getSubcategoria()->getSub_cod();
    $subTitle = $retornaProduto->getSubcategoria()->getSub_titulo();
    ?>
    <div class="main-panel">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#">Alterar Produto</a>
                </div>
                <?php
                require_once './inc/header_top.php';
                ?>
            </div>
        </nav>


        <div class="content">
            <div class="container-fluid">
                <div class="row">

                    <form method="post" enctype="multipart/form-data">
                        <div class="col-lg-8 col-md-7">
                            <div class="card">
                                <div class="header">
                                    <h4 class="title">Alterar Produto</h4>                               

                                </div>
                                <div class="content">
                                    <form>                                  
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label>Titulo do Produto</label>
                                                    <input type="text" class="form-control border-input" name="txtTitulo" placeholder="Produto" value="<?= $nome; ?>">
                                                </div>
                                            </div>                                    
                                        </div>                                    

                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="slCodRa">Código RA</label>
                                                    <input type="text" class="form-control border-input" name="slCodRa" placeholder="RA Produto" value="<?= $ra; ?>">
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="slVariacao">Variações</label>
                                                    <select name="slVariacao" id="slVariacao" class="form-control border-input">                                                     
                                                        <option value="<?= $varCod; ?>"><?= $varTitle; ?></option>

                                                        <?php
                                                        $lstVar = $variacaoController->todasVariacao();

                                                        if ($lstVar == NULL):
                                                            echo '<option value="">Não existem variações cadastradas</option>';
                                                        else:

                                                            foreach ($lstVar as $cat):
                                                                if ($cat->getTitulo_variavel() == $varTitle):

                                                                else:
                                                                    echo "<option value={$cat->getCod_variavel()}>{$cat->getTitulo_variavel()}</option>";
                                                                endif;
                                                            endforeach;

                                                        endif;
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="slOferta">Oferta</label>
                                                    <select name="slOferta" id="slOferta" class="form-control border-input">
                                                        <?php
                                                        if ($oferta == 1):
                                                            ?>
                                                            <option value="1" selected='selected'>Produto em oferta</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="2" selected='selected'>Produto não esta em oferta</option>
                                                        <?php
                                                        endif;
                                                        if ($oferta != 1):
                                                            ?>
                                                            <option value="1" <?php $oferta == 1 ? "selected='selected'" : "" ?>>Produto em oferta</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="2" <?php $oferta == 2 ? "selected='selected'" : "" ?>>Produto não esta em oferta</option>
                                                        <?php
                                                        endif;
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>


                                        <div class="row">
                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="slCategoria">Categoria</label>
                                                    <select id="slCategoria" name="slCategoria" class="form-control border-input">
                                                        <option value="<?= $categCod; ?>"><?= $categTitle; ?></option>                                                   

                                                        <?php
                                                        $listaCategoria = $categoriaController->ListarTodasCategorias(0, 200);

                                                        if ($listaCategoria == NULL):
                                                            echo '<option value="">Não existem categoria cadastradas</option>';
                                                        else:

                                                            foreach ($listaCategoria as $cat):
                                                                if ($cat->getTitulo() == $categTitle):

                                                                else:
                                                                    echo "<option value={$cat->getCod()}>{$cat->getTitulo()}</option>";
                                                                endif;
                                                            endforeach;

                                                        endif;
                                                        ?>

                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="slSubcategoria">Subcategoria</label>
                                                    <select name="slSubcategoria" id="slSubcategoria" class="form-control border-input">
                                                        <option value="<?= $subCod; ?>"><?= $subTitle; ?></option>
                                                    </select>
                                                </div>
                                            </div>                                           

                                            <div class="col-md-4">
                                                <div class="form-group">
                                                    <label for="slStatus">Status</label>
                                                    <select name="slStatus" id="slStatus" class="form-control border-input">
                                                        <?php
                                                        if ($status == 1):
                                                            ?>
                                                            <option value="1" selected='selected'>Ativo</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="2" selected='selected'>Bloqueado</option>
                                                        <?php
                                                        endif;
                                                        if ($status != 1):
                                                            ?>
                                                            <option value="1" <?php $status == 1 ? "selected='selected'" : "" ?>>Ativo</option>
                                                            <?php
                                                        else:
                                                            ?>
                                                            <option value="2" <?php $status == 2 ? "selected='selected'" : "" ?>>Bloqueado</option>
                                                        <?php
                                                        endif;
                                                        ?>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label for="txtMarca">Marca do Produto</label>
                                                    <input type="text" name="txtMarca" id="txtMarca" class="form-control border-input" placeholder="Marca do Produto" value="<?= $marca; ?>">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label>Descrição do Produto</label>
                                                    <textarea rows="3" name="txtDescricao" class="form-control border-input" placeholder="Descrição do produto" >
                                                        <?= $descricao; ?>
                                                    </textarea>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label for="txtValor_antigo">Valor Antigo</label>
                                                    <input type="text" name="txtValor_antigo" id="txtValor_antigo" class="form-control border-input" placeholder="Preço Antigo" value="<?= $valor_antigo; ?>">
                                                </div>
                                            </div>

                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label for="txtDesconto">Desconto</label>
                                                    <input type="text" name="txtDesconto" id="txtDesconto" class="form-control border-input" placeholder="6% de Desconto" value="<?= $desconto; ?>">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Preço R$ 1.000,00</label>
                                                    <input type="text" class="form-control border-input" name="txtPreco" placeholder="Código do Produto" value="<?= $preco; ?>">
                                                </div>
                                            </div>

                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Estoque</label>
                                                    <input type="text" class="form-control border-input" name="txtEstoque" placeholder="Código do Produto" value="<?= $estoque; ?>">
                                                </div>
                                            </div>

                                        </div>                               


                                        <div class="row">
                                            <div class="col-md-12">
                                                <?php echo $resultado; ?>
                                            </div>                                    
                                        </div>    


                                        <div class="text-center">
                                            <input type="submit" class="btn btn-success btn-fill btn-wd" name="btnCadastrar" value="Alterar Produto">
                                        </div>
                                        <div class="clearfix"></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </form>

                    <div class="col-lg-4 col-md-5">
                        <div class="card card-user">
                            <div class="image">
                                <?php
                                if ($thumb == null):
                                    echo '<img id="img-uploaded" src="assets/img/no_image.jpg" alt="Sua imagem">';
                                else:
                                    echo "<img id='img-uploaded' src='../upload/{$thumb}' alt='Sua imagem'>";
                                endif;
                                ?>                            
                            </div>                        
                        </div>


                        <div class="card">
                            <div class="row" id="image_preview">                               
                            </div>
                            <div class="content">                            
                                <div class="row">                                 
                                    <form action="" method="post" enctype="multipart/form-data">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>CAPA (JPG 800X1000PX):</label>
                                                <input type="file" class="form-control border-input uploader" id="imagemArtigo"  name="imagemArtigo">
                                            </div>
                                        </div>
                                        <div class="col-md-12 text-center">
                                            <input type="submit" class="btn btn-success btn-fill btn-wd" name='submitImage' value="Alterar Capa"/>
                                        </div>
                                    </form>                              
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        </div>
    <?php
    endif;
    ?>
    <script type="text/javascript">
        function preview_images()
        {
            var total_file = document.getElementById("images").files.length;
            for (var i = 0; i < total_file; i++)
            {
                $('#image_preview').append("<div class='col-md-3'><img class='img-responsive' src='" + URL.createObjectURL(event.target.files[i]) + "'></div>");
            }
        }
    </script>


