<?php
//instanciando as classes
$categoriaController = new CategoriaController();
$produtoController = new ProdutoController();
$variacaoController = new VariacaoController();

$produto = new Produto();
$helper = new Helper();
$upload = new Upload();

$resultado = "";
?>
<div class="main-panel">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar bar1"></span>
                    <span class="icon-bar bar2"></span>
                    <span class="icon-bar bar3"></span>
                </button>
                <a class="navbar-brand" href="?pagina=listarProduto">Listar Produtos</a>
            </div>
            <?php require_once './inc/header_top.php'; ?>
        </div>
    </nav>


    <div class="content">
        <div class="container-fluid">
            <div class="row">

                <form method="post" enctype="multipart/form-data">
                    <div class="col-lg-8 col-md-7">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">Cadastrar Novo Produto</h4>
                                <?php
                                $btnCadastrar = filter_input(INPUT_POST, 'btnCadastrar', FILTER_SANITIZE_STRING);
                                if ($btnCadastrar):
                                    $produto->setTitulo(filter_input(INPUT_POST, 'txtTitulo', FILTER_SANITIZE_STRING));
                                    $url = $helper->Name($produto->getTitulo());
                                    $produto->setUrl($url);
                                    $produto->setCategoria(filter_input(INPUT_POST, 'slCategoria', FILTER_SANITIZE_NUMBER_INT));
                                    $produto->setSubcategoria(filter_input(INPUT_POST, 'slSubcategoria', FILTER_SANITIZE_NUMBER_INT));
                                    $produto->setCod_ra(filter_input(INPUT_POST, 'slCodRa', FILTER_SANITIZE_STRING));
                                    $produto->setVariacao(filter_input(INPUT_POST, 'slVariacao', FILTER_SANITIZE_NUMBER_INT));
                                    $produto->setOferta(filter_input(INPUT_POST, 'slOferta', FILTER_SANITIZE_NUMBER_INT));
                                    $produto->setStatus(filter_input(INPUT_POST, 'slStatus', FILTER_SANITIZE_NUMBER_INT));
                                    $produto->setMarca_do_produto(filter_input(INPUT_POST, 'txtMarca', FILTER_SANITIZE_STRING));
                                    $produto->setDescricao(filter_input(INPUT_POST, 'txtDescricao', FILTER_SANITIZE_FULL_SPECIAL_CHARS));
                                    $produto->setValor(filter_input(INPUT_POST, 'txtValor', FILTER_SANITIZE_STRING));
                                    $produto->setValor_antigo(filter_input(INPUT_POST, 'txtValor_antigo', FILTER_SANITIZE_STRING));
                                    $produto->setDesconto(filter_input(INPUT_POST, 'txtDesconto', FILTER_SANITIZE_STRING));
                                    $produto->setEstoque(filter_input(INPUT_POST, 'txtEstoque', FILTER_SANITIZE_NUMBER_INT));
                                    $produto->setData(date('Y-m-d H:i:s'));

                                    //imagem esta recebendo files imagemArtigo
                                    $imagem = $_FILES['imagemArtigo'];
                                    $nomeProd = $helper->Name($produto->getTitulo());
                                    //recebendo a imagem, nome do post, tamanho da imagem, pasta
                                    $upload->Image($imagem, $nomeProd, 1000, 'produto');
                                    //setando a imagem
                                    $nomeImagem = $upload->getResult();
                                    $produto->setThumb($nomeImagem);
                                    //    //cadastro do produto
                                    if ($produtoController->Cadastrar($produto)):
                                        //header("location: ?pagina=listarProduto");
                                        $resultado = '<div class="alert alert-success">
                                                    <button type="button" aria-hidden="true" class="close">×</button>
                                                    <span><b> Cadastro efetuado com sucesso - </b></span>
                                                </div>';
                                    else:
                                        $resultado = '<div class="alert alert-danger">
                                                        <button type="button" aria-hidden="true" class="close">×</button>
                                                        <span><b> Erro ao cadastrar - Favor preencha todos os campos</b></span>
                                                    </div>';
                                    endif;
                                endif;
                                ?>
                            </div>

                            <div class="content">

                                <form method="post" enctype="multipart/form-data" id="frmCategoria" name="frmCategoria" novalidate onSubmit="return validaCadastro();" >
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>CAPA (JPG 800X1000PX):</label>
                                                <input type="file" class="form-control border-input uploader" id="imagemArtigo"  name="imagemArtigo">
                                            </div>
                                        </div>                                    
                                    </div>

                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Produto</label>
                                                <input type="text" name="txtTitulo" id="txtTitulo" class="form-control border-input" placeholder="Produto" value="">
                                                <span class="msg-error msg-titulo"></span>
                                            </div>
                                        </div>                                    
                                    </div>                                   

                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="slCodRa">Código RA</label>
                                                <input type="text" class="form-control border-input" name="slCodRa" placeholder="RA Produto" value="">
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="slVariacao">Variações</label>
                                                <select name="slVariacao" id="slVariacao" class="form-control border-input">                                                     

<?php
$lstVar = $variacaoController->todasVariacao();
if ($lstVar == null):
    echo '<option value="">Não existe variação!</option>';
else:
    echo '<option value="">Selecione Variação</option>';
    foreach ($lstVar as $var):
        ?>
                                                            <option value="<?= $var->getCod_variavel(); ?>"><?= $var->getTitulo_variavel(); ?></option>
                                                            <?php
                                                        endforeach;
                                                    endif;
                                                    ?>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="slOferta">Oferta</label>
                                                <select name="slOferta" id="slOferta" class="form-control border-input">                                                     
                                                    <option value="">Selecione Situação</option>
                                                    <option value="1">Em oferta</option>                                                        
                                                    <option value="2">Não esta em oferta</option>
                                                </select>
                                            </div>
                                        </div>                                        
                                    </div>

                                    <div class="row">
                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="slCategoria">Categoria</label>
                                                <select name="slCategoria" id="slCategoria" class="form-control border-input">
<?php
$listarCategoria = $categoriaController->ListarTodasCategorias(0, 200);
if ($listarCategoria == NULL):
    echo '<option value="">Não existem categoria cadastradas</option>';
else:
    echo '<option value="">Selecione a categoria</option>';
    foreach ($listarCategoria as $cat):
        ?>
                                                            <option value="<?= $cat->getCod(); ?>"><?= $cat->getTitulo(); ?></option>";
                                                            <?php
                                                        endforeach;
                                                    endif;
                                                    ?>

                                                </select>
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="slSubcategoria">Subcategoria</label>
                                                <select name="slSubcategoria" id="slSubcategoria" class="form-control border-input">
                                                    <option value="">Selecione a Subcategoria</option>
                                                </select>
                                            </div>
                                        </div>

                                        <div class="col-md-4">
                                            <div class="form-group">
                                                <label for="slStatus">Status</label>
                                                <select name="slStatus" id="slStatus" class="form-control border-input">
                                                    <option value="">Selecione o Status</option>
                                                    <option value="1">Ativo</option>
                                                    <option value="2">Bloqueado</option>
                                                </select>
                                            </div>
                                        </div>
                                        
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="txtMarca">Marca do Produto</label>
                                                <input type="text" name="txtMarca" id="txtMarca" class="form-control border-input" placeholder="Marca do Produto" value="">
                                            </div>
                                        </div> 

                                    </div>

                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Descrição do Produto</label>
                                                <textarea rows="3" name="txtDescricao" class="form-control border-input" placeholder="Descrição do produto" value="">
                                                </textarea>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="txtValor_antigo">Valor Antigo</label>
                                                <input type="text" name="txtValor_antigo" id="txtValor_antigo" class="form-control border-input" placeholder="Preço Antigo" value="">
                                            </div>
                                        </div>
                                        
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label for="txtDesconto">Desconto</label>
                                                <input type="text" name="txtDesconto" id="txtDesconto" class="form-control border-input" placeholder="6% de Desconto" value="">
                                            </div>
                                        </div>                                        
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Preço R$ 1.000,00</label>
                                                <input type="text" name="txtValor" class="form-control border-input" placeholder="Preço do Produto" value="">
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>Estoque</label>
                                                <input type="text" name="txtEstoque" class="form-control border-input" placeholder="Estoque do Produto" value="">
                                            </div>
                                        </div>

                                    </div>                                    
                                    <div class="row">
                                        <div class="col-md-12">
<?= $resultado; ?>
                                        </div>


                                    </div>                                    

                                    <div class="text-center">
                                        <input type="submit" class="btn btn-info btn-fill btn-wd" name="btnCadastrar" value="Cadastrar Produto"/>
                                        <a href="?pagina=listarProduto" class="btn btn-warning btn-fill btn-wd" >Listar Produto</a>
                                    </div>
                                    <div class="clearfix"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                </form>

                <div class="col-lg-4 col-md-5">
                    <div class="card card-user">
                        <div class="image">
                            <img id="img-uploaded" src="assets/img/no_image.jpg" alt="Sua imagem">
                        </div>                        
                    </div>
                    <div class="card">
                        <div class="row" id="image_preview">                               
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        function preview_images()
        {
            var total_file = document.getElementById("images").files.length;
            for (var i = 0; i < total_file; i++)
            {
                $('#image_preview').append("<div class='col-md-3'><img class='img-responsive' src='" + URL.createObjectURL(event.target.files[i]) + "'></div>");
            }
        }
    </script>



